### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by syedrazackimran** [mourke/PopcornKit#1]
```
        PopcornKit.movies(on: 1, filter: .date, genre: .all, query: nil, order: .descending) { error, movie in
            print(error)
            print(movie)

        }
        PopcornKit.randomMovie { error, movie in
            print(error)
            print(movie)

        }
        PopcornKit.movie(for: "tt1634106") { error, movie in
            print(error)
            print(movie)
        }

```
I am not getting any response. kindly let me know what I need to do more than that. 

I used pod to file to use your kit.

**Comment by mourke** [comment]
It looks like the API was taken down. You could host it yourself and change the API end point to point to your URL

**Comment by syedrazackimran** [comment]
where i need to change that endpoint. knidly lemme know.

**Comment by mourke** [comment]
The variable is`PCT_ENDPOINT_BASE` in `/PopcornKit/Private/PCTEndpoints.m`. Please note the repo you add must have the exact same repository structure as https://github.com/popcorn-official/popcorn-api used to (the api was taken down by the DMCA but you should be able to find a fork somewhere or on the internet archive)
